# https://bgstack15.wordpress.com/2016/03/24/adding-adfs-integration-to-apache/
# https://mattslifebytes.com/2018/08/07/protecting-internal-applications-with-a-saml-aware-reverse-proxy-a-tutorial/

# Install packages
sudo apt-get install apache2 libapache2-mod-auth-mellon

# Enable modules
sudo a2enmod auth_mellon authn_core authz_user

# get Federation Meta data
#wget https://adfs.lalgbtcenter.org/federationmetadata/2007-06/FederationMetadata.xml

# generate kyes
#wget https://raw.githubusercontent.com/UNINETT/mod_auth_mellon/master/mellon_create_metadata.sh
#bash mellon_create_metadata.sh urn:pharmcenter.lalgbtcenter.org "https://pharmcenter.lalgbtcenter.org/auth1/endpoint/"

# add some lines to the htaccess or vhost you are working on
Require Auth User
AuthType Mellon
MellonEnable auth
Require valid-user
MellonSamlResponseDump On # No ideas
MellonIdPMetadataFile /home/pharmcenter/public_html/mellon/FederationMetadata.xml # From IdP
MellonSPPrivateKeyFile /home/pharmcenter/public_html/mellon/urn_pharmcenter.lalgbtcenter.org.key # Generated by  mellon_create_metadata.sh
MellonSPCertFile /home/pharmcenter/public_html/mellon/urn_pharmcenter.lalgbtcenter.org.cert # Generated by  mellon_create_metadata.sh
MellonSPMetadataFile /home/pharmcenter/public_html/mellon/urn_pharmcenter.lalgbtcenter.org.xml # Generated by  mellon_create_metadata.sh
MellonMergeEnvVars On ":" # merge multi part variables (eg lists) into a single variable instead of _1, _2, etc
MellonEndpointPath /auth1/endpoint # End point used